# Generated by Django 3.2.15 on 2022-12-21 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page3', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='test',
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default='unnamed', max_length=255),
        ),
        migrations.AddField(
            model_name='category',
            name='tags',
            field=models.CharField(default='none', max_length=255),
        ),
    ]
