# Generated by Django 3.2.15 on 2022-12-22 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page3', '0002_auto_20221221_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='post_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='post_datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
